name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV
          echo "GITHUB_EVENT_PATH=${{ github.event_path }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          command_timeout: 4h
          script: |
            export GITHUB_EVENT_NAME=${{ github.event_name }}
            export GITHUB_EVENT_PATH=${{ github.event_path }}
            export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            export GITHUB_REPOSITORY=${{ github.repository }}
            export BRANCH_NAME=${{ github.head_ref || github.ref_name }}
            
            # Debugging information
            echo "GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}"
            echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
            echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
            echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"
            echo "BRANCH_NAME=${BRANCH_NAME}"
            
            if [ "${GITHUB_EVENT_NAME}" = "release" ]; then
              echo "Running release script"
              bash ./run_release.sh
            else
              echo "Running build script"
              bash ./run_build.sh
            fi
